
version: '3.8'

services:
  aiengine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinite-adventure-engine
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Authenticate Google Cloud SDK (Secret Manager)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
    volumes:
      # Mount the local Service Account Key into the container
      - ./gcp-key.json:/app/gcp-key.json:ro
