type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type GameSession @table {
  name: String!
  createdAt: Timestamp!
  lastPlayedAt: Timestamp!
  creator: User
  description: String
  genre: String
  public: Boolean
}

type Character @table {
  name: String!
  characterClass: String!
  backstory: String!
  createdAt: Timestamp!
  owner: User
  gameSession: GameSession
  attributes: String
  inventory: String
}

type GameTurn @table {
  turnNumber: Int!
  playerInput: String!
  gmResponse: String!
  createdAt: Timestamp!
  gameSession: GameSession
  player: User
  triggeredEvents: String
}

type Setting @table {
  name: String!
  description: String!
  createdAt: Timestamp!
  creator: User
  genre: String
  loreElements: String
}